"""
spatial_graph.py — Technology-Aware Spatial Graph Builder

Builds spatial k-NN or radius graphs from processed spot/cell coordinates.
Fixed from src3:
  - Technology-aware k and max_distance defaults
  - Distances normalised by spot_diameter (technology-specific)
  - MERFISH/cell-level technologies use radius-based graph by default
  - k and radius read from config or tech_profile.json (not hard-coded)

Usage:
    python -m mosanic.data.spatial_graph \
        --config configs/breast_config.yaml \
        --dataset breast_new
"""

import numpy as np
from pathlib import Path
from typing import Dict, Optional, Tuple
from sklearn.neighbors import NearestNeighbors, radius_neighbors_graph
import json
import yaml
import logging

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Technology-specific defaults
# ---------------------------------------------------------------------------
TECH_DEFAULTS = {
    'visium': {
        'method': 'knn',
        'k': 6,                   # Hexagonal grid → 6 direct neighbours
        'spot_diameter_um': 55.0,
        'max_distance_um': 200.0, # ~2 spot-diameters (avoids false juxtacrine)
        'normalise_by_diameter': True,
    },
    'visium_hd': {
        'method': 'knn',
        'k': 8,
        'spot_diameter_um': 2.0,
        'max_distance_um': 20.0,
        'normalise_by_diameter': True,
    },
    'merfish': {
        'method': 'radius',       # Cells are not on a regular grid
        'radius_um': 50.0,
        'spot_diameter_um': 10.0, # Approximate cell diameter
        'max_distance_um': 50.0,
        'normalise_by_diameter': True,
    },
    'slide_seq': {
        'method': 'knn',
        'k': 8,
        'spot_diameter_um': 10.0,
        'max_distance_um': 30.0,
        'normalise_by_diameter': True,
    },
    'stereo_seq': {
        'method': 'knn',
        'k': 8,
        'spot_diameter_um': 1.0,  # After bin aggregation
        'max_distance_um': 10.0,
        'normalise_by_diameter': True,
    },
    'cosmx': {
        'method': 'radius',
        'radius_um': 30.0,
        'spot_diameter_um': 10.0,
        'max_distance_um': 30.0,
        'normalise_by_diameter': True,
    },
}


class SpatialGraphBuilder:
    """Build technology-aware spatial graphs from processed spot/cell coordinates."""

    def __init__(self, config_path: str, dataset: str):
        """
        Args:
            config_path: Path to config YAML
            dataset:     Dataset name (breast_new | colorectal | …)
        """
        with open(config_path) as f:
            self.config = yaml.safe_load(f)
        self.dataset = dataset
        self.data_dir = Path(self.config['data']['processed_dir']) / dataset

        self.coords = None
        self.edge_index = None
        self.distances = None
        self.statistics = {}
        self.tech_profile = {}

        logger.info(f"SpatialGraphBuilder: dataset={dataset}")

    def _load_tech_profile(self) -> Dict:
        """Load technology profile generated by technology_handler.py."""
        profile_path = self.data_dir / 'tech_profile.json'
        if profile_path.exists():
            with open(profile_path) as f:
                self.tech_profile = json.load(f)
            logger.info(f"Tech profile: {self.tech_profile.get('technology', 'unknown')}")
        else:
            logger.warning(
                f"tech_profile.json not found at {profile_path}. "
                "Defaulting to Visium parameters. Run technology_handler.py first."
            )
            self.tech_profile = {'technology': 'visium'}
        return self.tech_profile

    def _get_tech_params(self) -> Dict:
        """Merge config spatial params with technology-specific defaults."""
        tech = self.tech_profile.get('technology', 'visium').lower()
        defaults = TECH_DEFAULTS.get(tech, TECH_DEFAULTS['visium'])

        # Config overrides defaults
        cfg_spatial = self.config.get('spatial', {})
        params = {
            'method':              cfg_spatial.get('graph_method',    defaults['method']),
            'k':                   cfg_spatial.get('k_neighbors',     defaults.get('k', 6)),
            'radius_um':           cfg_spatial.get('radius_um',       defaults.get('radius_um', 100.0)),
            'spot_diameter_um':    self.tech_profile.get('spot_diameter_um',
                                       defaults['spot_diameter_um']),
            'max_distance_um':     cfg_spatial.get('max_distance_um', defaults['max_distance_um']),
            'normalise_by_diameter': defaults['normalise_by_diameter'],
            'distance_metric':     cfg_spatial.get('distance_metric', 'euclidean'),
        }
        logger.info(f"Spatial params ({tech}): {params}")
        return params

    def load_coordinates(self) -> np.ndarray:
        coords_path = self.data_dir / 'spatial_coordinates.npy'
        if not coords_path.exists():
            raise FileNotFoundError(
                f"Spatial coordinates not found: {coords_path}\n"
                "Run anndata_loader.py first."
            )
        self.coords = np.load(coords_path)
        logger.info(f"Loaded coordinates: {self.coords.shape}")
        return self.coords

    # ------------------------------------------------------------------
    # Graph construction
    # ------------------------------------------------------------------
    def build_spatial_graph(self) -> Tuple[np.ndarray, np.ndarray]:
        """
        Build spatial graph using technology-appropriate parameters.

        Returns:
            edge_index: [2, E] integer array
            distances:  [E] float array in micrometers
        """
        self._load_tech_profile()
        if self.coords is None:
            self.load_coordinates()
        params = self._get_tech_params()

        if params['method'] == 'knn':
            self._build_knn(k=params['k'], metric=params['distance_metric'])
        else:
            self._build_radius(radius_um=params['radius_um'], metric=params['distance_metric'])

        # Enforce max distance cutoff
        if params['max_distance_um'] > 0:
            mask = self.distances <= params['max_distance_um']
            self.edge_index = self.edge_index[:, mask]
            self.distances  = self.distances[mask]
            logger.info(f"After max_distance filter ({params['max_distance_um']} µm): "
                        f"{self.edge_index.shape[1]} edges remain")

        # Symmetrize
        self._make_undirected()

        # Normalise distances by spot diameter (0 = touching, 1 = 1 spot apart, etc.)
        if params['normalise_by_diameter'] and params['spot_diameter_um'] > 0:
            self.distances_normalised = self.distances / params['spot_diameter_um']
        else:
            self.distances_normalised = self.distances.copy()

        return self.edge_index, self.distances

    def _build_knn(self, k: int, metric: str = 'euclidean'):
        logger.info(f"Building k-NN graph (k={k}, metric={metric}) ...")
        knn = NearestNeighbors(n_neighbors=k + 1, metric=metric, algorithm='auto', n_jobs=-1)
        knn.fit(self.coords)
        dists_all, idxs = knn.kneighbors(self.coords)

        src, dst, dvals = [], [], []
        for i in range(len(self.coords)):
            for j_pos in range(1, k + 1):   # skip self (index 0)
                j = idxs[i, j_pos]
                d = dists_all[i, j_pos]
                src.append(i); dst.append(j); dvals.append(d)

        self.edge_index = np.array([src, dst], dtype=np.int64)
        self.distances  = np.array(dvals, dtype=np.float32)
        logger.info(f"k-NN: {self.edge_index.shape[1]} directed edges")

    def _build_radius(self, radius_um: float, metric: str = 'euclidean'):
        logger.info(f"Building radius graph (r={radius_um} µm, metric={metric}) ...")
        adj = radius_neighbors_graph(
            self.coords, radius=radius_um, mode='distance',
            metric=metric, include_self=False, n_jobs=-1
        )
        coo = adj.tocoo()
        self.edge_index = np.vstack([coo.row, coo.col]).astype(np.int64)
        self.distances  = coo.data.astype(np.float32)
        logger.info(f"Radius graph: {self.edge_index.shape[1]} directed edges")

    def _make_undirected(self):
        """Symmetrize: for each (i,j), ensure (j,i) exists. Keep min distance."""
        edge_dict = {}
        for k in range(self.edge_index.shape[1]):
            s, t, d = int(self.edge_index[0, k]), int(self.edge_index[1, k]), float(self.distances[k])
            for key in [(s, t), (t, s)]:
                if key not in edge_dict or d < edge_dict[key]:
                    edge_dict[key] = d
        edges = list(edge_dict.keys())
        self.edge_index = np.array(edges, dtype=np.int64).T
        self.distances  = np.array([edge_dict[e] for e in edges], dtype=np.float32)
        logger.info(f"After symmetrization: {self.edge_index.shape[1]} undirected edges")

    # ------------------------------------------------------------------
    # Statistics
    # ------------------------------------------------------------------
    def compute_statistics(self) -> Dict:
        n = self.coords.shape[0]
        deg = np.bincount(self.edge_index[0], minlength=n)
        self.statistics = {
            'num_nodes':  int(n),
            'num_edges':  int(self.edge_index.shape[1]),
            'avg_degree': float(deg.mean()),
            'isolated':   int((deg == 0).sum()),
            'distance_mean_um':   float(self.distances.mean()),
            'distance_median_um': float(np.median(self.distances)),
            'distance_max_um':    float(self.distances.max()),
            'technology':         self.tech_profile.get('technology', 'unknown'),
        }
        logger.info(
            f"Graph stats: {n} nodes, {self.edge_index.shape[1]} edges, "
            f"avg_deg={self.statistics['avg_degree']:.2f}"
        )
        return self.statistics

    # ------------------------------------------------------------------
    # Save
    # ------------------------------------------------------------------
    def save(self):
        out = self.data_dir
        np.save(out / 'spatial_edge_index.npy',         self.edge_index)
        np.save(out / 'spatial_edge_distances.npy',      self.distances)
        np.save(out / 'spatial_edge_distances_norm.npy', self.distances_normalised)
        if self.statistics:
            with open(out / 'spatial_graph_statistics.json', 'w') as f:
                json.dump(self.statistics, f, indent=2)
        logger.info(f"Spatial graph saved to {out}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def main():
    import argparse
    parser = argparse.ArgumentParser(description='Build technology-aware spatial graph')
    parser.add_argument('--config',  required=True, help='Config YAML path')
    parser.add_argument('--dataset', required=True, help='Dataset name')
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO,
                        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')

    builder = SpatialGraphBuilder(config_path=args.config, dataset=args.dataset)
    builder.load_coordinates()
    builder.build_spatial_graph()
    builder.compute_statistics()
    builder.save()
    logger.info("Done.")


if __name__ == '__main__':
    main()
